"""
main.py
-------
LexFlow FastAPI application entry point.
- Mounts all routers
- Configures CORS for React frontend (localhost:5173)
- Initialises SQLite database on startup
- Provides /auth/login and /auth/register endpoints
- Swagger UI available at /docs
"""

import os
import secrets
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from database.db import init_db, get_connection
from auth.auth import (
    authenticate_user,
    create_access_token,
    hash_password,
    get_current_user,
)
from auth.roles import require_admin
from routes import cases, extraction, quiz, verification, dashboard

# ── App factory ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="LexFlow API",
    description="AI-Powered Court Judgment Intelligence System",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS ──────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite dev server
        "http://localhost:3000",   # fallback
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Serve uploaded PDFs as static files ───────────────────────────────────────
os.makedirs("uploads", exist_ok=True)
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")

# ── Mount routers ─────────────────────────────────────────────────────────────
app.include_router(cases.router)
app.include_router(extraction.router)
app.include_router(quiz.router)
app.include_router(verification.router)
app.include_router(dashboard.router)


# ── Startup: initialise DB ───────────────────────────────────────────────────
@app.on_event("startup")
def on_startup():
    init_db()
    _seed_demo_users()


def _seed_demo_users():
    """
    Create demo users if DB is empty.
    Demo credentials:
      admin@lexflow.com   / admin123   → role: admin
      student@lexflow.com / student123 → role: student
      official@lexflow.com/ official123→ role: official
    """
    conn = get_connection()
    count = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
    if count == 0:
        demos = [
            ("Admin User",    "admin@lexflow.com",    "admin123",    "admin"),
            ("Law Student",   "student@lexflow.com",  "student123",  "student"),
            ("Govt Official", "official@lexflow.com", "official123", "official"),
        ]
        for name, email, pwd, role in demos:
            conn.execute(
                "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
                (name, email, hash_password(pwd), role),
            )
        conn.commit()
        print("✅  Demo users seeded (admin / student / official)")
    conn.close()


# ── Auth endpoints ────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    email: str
    password: str


class RegisterRequest(BaseModel):
    name: str
    email: str
    password: str
    role: str = "student"         # default role
    invite_code: str | None = None


@app.post("/auth/login", tags=["Auth"])
def login(body: LoginRequest):
    """
    Authenticate user with email + password.
    Returns JWT token + user info (role determines frontend redirect).
    """
    user = authenticate_user(body.email, body.password)
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password.",
        )
    token = create_access_token(user["id"], user["email"], user["role"])
    return {
        "access_token": token,
        "token_type": "bearer",
        "user": {
            "id": user["id"],
            "name": user["name"],
            "email": user["email"],
            "role": user["role"],
        },
    }


@app.post("/auth/register", tags=["Auth"])
def register(body: RegisterRequest):
    """
    Register a new user.
    Students require a valid invite_code (generated by admin).
    Admin/Official accounts can only be created by existing admins in production.
    """
    conn = get_connection()

    # Check email uniqueness
    existing = conn.execute(
        "SELECT id FROM users WHERE email = ?", (body.email,)
    ).fetchone()
    if existing:
        conn.close()
        raise HTTPException(status_code=400, detail="Email already registered.")

    # Validate invite code for student role
    if body.role == "student" and body.invite_code:
        valid = conn.execute(
            "SELECT id FROM users WHERE invite_code = ?", (body.invite_code,)
        ).fetchone()
        if not valid:
            conn.close()
            raise HTTPException(status_code=403, detail="Invalid invite code.")

    conn.execute(
        "INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)",
        (body.name, body.email, hash_password(body.password), body.role),
    )
    conn.commit()
    conn.close()
    return {"message": "Account created successfully. Please log in."}


@app.post("/auth/invite", tags=["Auth"])
def generate_invite(current_user: dict = Depends(require_admin)):
    """Admin generates a one-time invite code for a student."""
    code = secrets.token_urlsafe(12)
    conn = get_connection()
    conn.execute(
        "UPDATE users SET invite_code = ? WHERE id = ?",
        (code, current_user["id"]),
    )
    conn.commit()
    conn.close()
    return {"invite_code": code}


@app.get("/auth/me", tags=["Auth"])
def me(current_user: dict = Depends(get_current_user)):
    """Return current user info from JWT."""
    return current_user


# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/health", tags=["System"])
def health():
    return {"status": "ok", "service": "LexFlow API"}
